import { Footer } from '@/components/Footer/Footer';
import { Header } from '@/components/Header/Header';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import styles from './layout.module.css';
import '@/styles/globals.scss';
import { ReactNode } from 'react';
import { MenuProvider } from '@/context/app.context';
import { UpButton } from '@/components/UpButton/UpButton';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MenuProvider firstCategory={0}>
          <div className={styles.wrapper}>
            <Header className={styles.header} />
            <Sidebar className={styles.sidebar} />
            <div className={styles.content}>{children}</div>
            <Footer className={styles.footer} />
            <UpButton appearance="primary" arrow="up" />
          </div>
        </MenuProvider>
      </body>
    </html>
  );
}
